// Catálogo maestro de todos los tipos de documentos operativos de Salud San Marcos.
// Este archivo se duplica en server/src y client/src (sin dependencias de build cruzadas).
// Si se agrega o modifica un tipo de documento, actualizar las 3 copias.

export type Familia = 'comercial' | 'acta' | 'comprobante';
export type Contraparte = 'cliente' | 'proveedor' | 'interno' | 'ninguno';

export interface CampoExtra {
  name: string;
  label: string;
  type: 'text' | 'textarea' | 'date' | 'number' | 'select' | 'time';
  options?: string[];
  required?: boolean;
  placeholder?: string;
}

export interface DocumentTypeConfig {
  key: string;
  label: string;
  labelPlural: string;
  prefijo: string;
  familia: Familia;
  fiscal: boolean;
  numeroControl: boolean;
  contraparte: Contraparte;
  tieneItems: boolean;
  itemsConPrecio: boolean;
  tieneFirmantes: boolean;
  tieneReferencia: boolean;
  referenciaTipos?: string[];
  camposExtra: CampoExtra[];
  tituloImpresion: string;
  grupoMenu: 'Comercial' | 'Depósito y Logística' | 'Administrativo';
}

export const DOCUMENT_TYPES: DocumentTypeConfig[] = [
  {
    key: 'orden_compra',
    label: 'Orden de Compra',
    labelPlural: 'Órdenes de Compra',
    prefijo: 'OC',
    familia: 'comercial',
    fiscal: false,
    numeroControl: false,
    contraparte: 'proveedor',
    tieneItems: true,
    itemsConPrecio: true,
    tieneFirmantes: false,
    tieneReferencia: false,
    camposExtra: [
      { name: 'condicionesPago', label: 'Condiciones de pago', type: 'text', placeholder: 'Ej: Contado / 30 días' },
      { name: 'lugarEntrega', label: 'Lugar de entrega', type: 'text' },
      { name: 'fechaRequerida', label: 'Fecha requerida de entrega', type: 'date' },
    ],
    tituloImpresion: 'ORDEN DE COMPRA',
    grupoMenu: 'Comercial',
  },
  {
    key: 'cotizacion',
    label: 'Cotización',
    labelPlural: 'Cotizaciones',
    prefijo: 'COT',
    familia: 'comercial',
    fiscal: false,
    numeroControl: false,
    contraparte: 'cliente',
    tieneItems: true,
    itemsConPrecio: true,
    tieneFirmantes: false,
    tieneReferencia: false,
    camposExtra: [
      { name: 'validezDias', label: 'Validez de la oferta (días)', type: 'number', placeholder: '15' },
      { name: 'condicionesPago', label: 'Condiciones de pago', type: 'text' },
      { name: 'tiempoEntrega', label: 'Tiempo de entrega', type: 'text' },
    ],
    tituloImpresion: 'COTIZACIÓN',
    grupoMenu: 'Comercial',
  },
  {
    key: 'factura',
    label: 'Factura',
    labelPlural: 'Facturas',
    prefijo: 'FAC',
    familia: 'comercial',
    fiscal: true,
    numeroControl: true,
    contraparte: 'cliente',
    tieneItems: true,
    itemsConPrecio: true,
    tieneFirmantes: false,
    tieneReferencia: false,
    camposExtra: [
      { name: 'condicionesPago', label: 'Condición de pago', type: 'select', options: ['Contado', 'Crédito'] },
      { name: 'formaPago', label: 'Forma de pago', type: 'text', placeholder: 'Transferencia, efectivo, etc.' },
    ],
    tituloImpresion: 'FACTURA',
    grupoMenu: 'Comercial',
  },
  {
    key: 'nota_entrega',
    label: 'Nota de Entrega',
    labelPlural: 'Notas de Entrega',
    prefijo: 'NE',
    familia: 'comercial',
    fiscal: false,
    numeroControl: false,
    contraparte: 'cliente',
    tieneItems: true,
    itemsConPrecio: false,
    tieneFirmantes: true,
    tieneReferencia: true,
    referenciaTipos: ['factura', 'orden_compra'],
    camposExtra: [{ name: 'transportista', label: 'Transportista / Vehículo', type: 'text' }],
    tituloImpresion: 'NOTA DE ENTREGA',
    grupoMenu: 'Comercial',
  },
  {
    key: 'nota_credito',
    label: 'Nota de Crédito',
    labelPlural: 'Notas de Crédito',
    prefijo: 'NC',
    familia: 'comercial',
    fiscal: true,
    numeroControl: true,
    contraparte: 'cliente',
    tieneItems: true,
    itemsConPrecio: true,
    tieneFirmantes: false,
    tieneReferencia: true,
    referenciaTipos: ['factura'],
    camposExtra: [{ name: 'motivo', label: 'Motivo', type: 'textarea', required: true }],
    tituloImpresion: 'NOTA DE CRÉDITO',
    grupoMenu: 'Comercial',
  },
  {
    key: 'nota_debito',
    label: 'Nota de Débito',
    labelPlural: 'Notas de Débito',
    prefijo: 'ND',
    familia: 'comercial',
    fiscal: true,
    numeroControl: true,
    contraparte: 'cliente',
    tieneItems: true,
    itemsConPrecio: true,
    tieneFirmantes: false,
    tieneReferencia: true,
    referenciaTipos: ['factura'],
    camposExtra: [{ name: 'motivo', label: 'Motivo', type: 'textarea', required: true }],
    tituloImpresion: 'NOTA DE DÉBITO',
    grupoMenu: 'Comercial',
  },
  {
    key: 'recibo_pago',
    label: 'Recibo de Pago',
    labelPlural: 'Recibos de Pago',
    prefijo: 'REC',
    familia: 'comprobante',
    fiscal: false,
    numeroControl: false,
    contraparte: 'cliente',
    tieneItems: false,
    itemsConPrecio: false,
    tieneFirmantes: false,
    tieneReferencia: true,
    referenciaTipos: ['factura'],
    camposExtra: [
      { name: 'monto', label: 'Monto recibido', type: 'number', required: true },
      { name: 'formaPago', label: 'Forma de pago', type: 'select', options: ['Efectivo', 'Transferencia', 'Pago móvil', 'Zelle', 'Cheque', 'Otro'] },
      { name: 'referenciaPago', label: 'N° de referencia / operación', type: 'text' },
      { name: 'concepto', label: 'Concepto', type: 'textarea' },
    ],
    tituloImpresion: 'RECIBO DE PAGO',
    grupoMenu: 'Comercial',
  },
  {
    key: 'comprobante_pago',
    label: 'Comprobante de Pago',
    labelPlural: 'Comprobantes de Pago',
    prefijo: 'CP',
    familia: 'comprobante',
    fiscal: false,
    numeroControl: false,
    contraparte: 'proveedor',
    tieneItems: false,
    itemsConPrecio: false,
    tieneFirmantes: false,
    tieneReferencia: false,
    camposExtra: [
      { name: 'monto', label: 'Monto pagado', type: 'number', required: true },
      { name: 'formaPago', label: 'Forma de pago', type: 'select', options: ['Efectivo', 'Transferencia', 'Pago móvil', 'Zelle', 'Cheque', 'Otro'] },
      { name: 'referenciaPago', label: 'N° de referencia / operación', type: 'text' },
      { name: 'concepto', label: 'Concepto / factura asociada', type: 'textarea' },
    ],
    tituloImpresion: 'COMPROBANTE DE PAGO',
    grupoMenu: 'Administrativo',
  },
  {
    key: 'retencion_iva',
    label: 'Comprobante de Retención de IVA',
    labelPlural: 'Retenciones de IVA',
    prefijo: 'RIVA',
    familia: 'comprobante',
    fiscal: true,
    numeroControl: false,
    contraparte: 'proveedor',
    tieneItems: false,
    itemsConPrecio: false,
    tieneFirmantes: false,
    tieneReferencia: true,
    referenciaTipos: ['factura'],
    camposExtra: [
      { name: 'numeroFacturaProveedor', label: 'N° de factura del proveedor', type: 'text', required: true },
      { name: 'numeroControlProveedor', label: 'N° de control de la factura', type: 'text' },
      { name: 'totalCompra', label: 'Total de la compra (Bs.)', type: 'number', required: true },
      { name: 'baseImponibleRet', label: 'Base imponible', type: 'number', required: true },
      { name: 'ivaFacturado', label: 'IVA facturado', type: 'number', required: true },
      { name: 'porcentajeRetencion', label: '% de retención', type: 'select', options: ['75', '100'] },
      { name: 'ivaRetenido', label: 'IVA retenido', type: 'number', required: true },
    ],
    tituloImpresion: 'COMPROBANTE DE RETENCIÓN DE IVA',
    grupoMenu: 'Administrativo',
  },
  {
    key: 'requisicion_compra',
    label: 'Requisición de Compra',
    labelPlural: 'Requisiciones de Compra',
    prefijo: 'RC',
    familia: 'comercial',
    fiscal: false,
    numeroControl: false,
    contraparte: 'interno',
    tieneItems: true,
    itemsConPrecio: false,
    tieneFirmantes: true,
    tieneReferencia: false,
    camposExtra: [
      { name: 'departamento', label: 'Departamento / Área solicitante', type: 'text' },
      { name: 'justificacion', label: 'Justificación', type: 'textarea' },
      { name: 'fechaNecesidad', label: 'Fecha en que se necesita', type: 'date' },
    ],
    tituloImpresion: 'REQUISICIÓN DE COMPRA',
    grupoMenu: 'Administrativo',
  },
  {
    key: 'orden_servicio',
    label: 'Orden de Servicio',
    labelPlural: 'Órdenes de Servicio',
    prefijo: 'OS',
    familia: 'comercial',
    fiscal: false,
    numeroControl: false,
    contraparte: 'proveedor',
    tieneItems: true,
    itemsConPrecio: true,
    tieneFirmantes: false,
    tieneReferencia: false,
    camposExtra: [
      { name: 'descripcionServicio', label: 'Descripción general del servicio', type: 'textarea' },
      { name: 'lugarPrestacion', label: 'Lugar de prestación del servicio', type: 'text' },
      { name: 'plazoEjecucion', label: 'Plazo de ejecución', type: 'text' },
    ],
    tituloImpresion: 'ORDEN DE SERVICIO',
    grupoMenu: 'Comercial',
  },
  {
    key: 'guia_despacho',
    label: 'Guía de Despacho',
    labelPlural: 'Guías de Despacho',
    prefijo: 'GD',
    familia: 'comercial',
    fiscal: false,
    numeroControl: false,
    contraparte: 'cliente',
    tieneItems: true,
    itemsConPrecio: false,
    tieneFirmantes: true,
    tieneReferencia: true,
    referenciaTipos: ['factura', 'nota_entrega', 'orden_compra'],
    camposExtra: [
      { name: 'transportista', label: 'Transportista', type: 'text' },
      { name: 'vehiculoPlaca', label: 'Vehículo / Placa', type: 'text' },
      { name: 'conductorCedula', label: 'Conductor / Cédula', type: 'text' },
      { name: 'origenDestino', label: 'Origen - Destino', type: 'text' },
    ],
    tituloImpresion: 'GUÍA DE DESPACHO',
    grupoMenu: 'Depósito y Logística',
  },
  {
    key: 'acta_recepcion',
    label: 'Acta de Recepción de Mercancía',
    labelPlural: 'Actas de Recepción',
    prefijo: 'ARM',
    familia: 'acta',
    fiscal: false,
    numeroControl: false,
    contraparte: 'proveedor',
    tieneItems: true,
    itemsConPrecio: false,
    tieneFirmantes: true,
    tieneReferencia: true,
    referenciaTipos: ['orden_compra'],
    camposExtra: [
      { name: 'lugar', label: 'Lugar', type: 'text' },
      { name: 'hora', label: 'Hora', type: 'time' },
      { name: 'condicionMercancia', label: 'Condición de la mercancía recibida', type: 'select', options: ['Conforme', 'Conforme con observaciones', 'No conforme'] },
      { name: 'observaciones', label: 'Observaciones', type: 'textarea' },
    ],
    tituloImpresion: 'ACTA DE RECEPCIÓN DE MERCANCÍA',
    grupoMenu: 'Depósito y Logística',
  },
  {
    key: 'acta_entrega',
    label: 'Acta de Entrega',
    labelPlural: 'Actas de Entrega',
    prefijo: 'AE',
    familia: 'acta',
    fiscal: false,
    numeroControl: false,
    contraparte: 'cliente',
    tieneItems: true,
    itemsConPrecio: false,
    tieneFirmantes: true,
    tieneReferencia: true,
    referenciaTipos: ['nota_entrega', 'orden_compra', 'orden_servicio'],
    camposExtra: [
      { name: 'lugar', label: 'Lugar', type: 'text' },
      { name: 'hora', label: 'Hora', type: 'time' },
      { name: 'observaciones', label: 'Observaciones', type: 'textarea' },
    ],
    tituloImpresion: 'ACTA DE ENTREGA',
    grupoMenu: 'Depósito y Logística',
  },
  {
    key: 'acta_almacen',
    label: 'Acta de Depósito',
    labelPlural: 'Actas de Depósito',
    prefijo: 'AA',
    familia: 'acta',
    fiscal: false,
    numeroControl: false,
    contraparte: 'interno',
    tieneItems: true,
    itemsConPrecio: false,
    tieneFirmantes: true,
    tieneReferencia: false,
    camposExtra: [
      { name: 'tipoMovimiento', label: 'Tipo de movimiento', type: 'select', options: ['Ajuste', 'Traslado interno', 'Merma', 'Devolución', 'Otro'] },
      { name: 'ubicacion', label: 'Ubicación / Depósito', type: 'text' },
      { name: 'motivo', label: 'Motivo', type: 'textarea' },
    ],
    tituloImpresion: 'ACTA DE DEPÓSITO',
    grupoMenu: 'Depósito y Logística',
  },
  {
    key: 'vale_salida',
    label: 'Vale de Salida de Depósito',
    labelPlural: 'Vales de Salida',
    prefijo: 'VS',
    familia: 'comprobante',
    fiscal: false,
    numeroControl: false,
    contraparte: 'interno',
    tieneItems: true,
    itemsConPrecio: false,
    tieneFirmantes: true,
    tieneReferencia: false,
    camposExtra: [
      { name: 'destino', label: 'Destino / Departamento que retira', type: 'text' },
      { name: 'motivo', label: 'Motivo de la salida', type: 'textarea' },
      { name: 'responsableRetira', label: 'Responsable que retira', type: 'text' },
    ],
    tituloImpresion: 'VALE DE SALIDA DE DEPÓSITO',
    grupoMenu: 'Depósito y Logística',
  },
  {
    key: 'vale_entrada',
    label: 'Vale de Entrada de Depósito',
    labelPlural: 'Vales de Entrada',
    prefijo: 'VE',
    familia: 'comprobante',
    fiscal: false,
    numeroControl: false,
    contraparte: 'interno',
    tieneItems: true,
    itemsConPrecio: false,
    tieneFirmantes: true,
    tieneReferencia: true,
    referenciaTipos: ['orden_compra', 'acta_recepcion'],
    camposExtra: [
      { name: 'origen', label: 'Origen', type: 'text' },
      { name: 'motivo', label: 'Motivo del ingreso', type: 'textarea' },
      { name: 'responsableRecibe', label: 'Responsable que recibe', type: 'text' },
    ],
    tituloImpresion: 'VALE DE ENTRADA DE DEPÓSITO',
    grupoMenu: 'Depósito y Logística',
  },
  {
    key: 'acta_inventario',
    label: 'Acta de Inventario',
    labelPlural: 'Actas de Inventario',
    prefijo: 'AI',
    familia: 'acta',
    fiscal: false,
    numeroControl: false,
    contraparte: 'interno',
    tieneItems: true,
    itemsConPrecio: false,
    tieneFirmantes: true,
    tieneReferencia: false,
    camposExtra: [
      { name: 'ubicacion', label: 'Ubicación / Depósito', type: 'text' },
      { name: 'periodo', label: 'Período de conteo', type: 'text' },
      { name: 'conclusion', label: 'Conclusión / Diferencias encontradas', type: 'textarea' },
    ],
    tituloImpresion: 'ACTA DE INVENTARIO',
    grupoMenu: 'Depósito y Logística',
  },
  {
    key: 'acta_control_activo',
    label: 'Acta de Control de Activo',
    labelPlural: 'Actas de Control de Activos',
    prefijo: 'ACA',
    familia: 'acta',
    fiscal: false,
    numeroControl: false,
    contraparte: 'interno',
    tieneItems: false,
    itemsConPrecio: false,
    tieneFirmantes: true,
    tieneReferencia: false,
    camposExtra: [
      { name: 'tipoMovimiento', label: 'Tipo de movimiento', type: 'select', options: ['Asignación', 'Traslado', 'Mantenimiento', 'Baja', 'Otro'], required: true },
      { name: 'codigoActivo', label: 'Código del activo', type: 'text', required: true },
      { name: 'descripcionActivo', label: 'Descripción del activo', type: 'text', required: true },
      { name: 'ubicacion', label: 'Ubicación', type: 'text' },
      { name: 'responsable', label: 'Responsable asignado', type: 'text' },
      { name: 'observacionesMovimiento', label: 'Observaciones', type: 'textarea' },
    ],
    tituloImpresion: 'ACTA DE CONTROL DE ACTIVO',
    grupoMenu: 'Depósito y Logística',
  },
  {
    key: 'acta_reunion',
    label: 'Acta de Reunión',
    labelPlural: 'Actas de Reunión',
    prefijo: 'AR',
    familia: 'acta',
    fiscal: false,
    numeroControl: false,
    contraparte: 'ninguno',
    tieneItems: false,
    itemsConPrecio: false,
    tieneFirmantes: true,
    tieneReferencia: false,
    camposExtra: [
      { name: 'lugar', label: 'Lugar', type: 'text' },
      { name: 'hora', label: 'Hora', type: 'time' },
      { name: 'asistentes', label: 'Asistentes (uno por línea)', type: 'textarea' },
      { name: 'agenda', label: 'Agenda / Puntos tratados', type: 'textarea' },
      { name: 'acuerdos', label: 'Acuerdos y compromisos', type: 'textarea' },
    ],
    tituloImpresion: 'ACTA DE REUNIÓN',
    grupoMenu: 'Administrativo',
  },
];

export function getDocumentType(key: string): DocumentTypeConfig | undefined {
  return DOCUMENT_TYPES.find((t) => t.key === key);
}
